[package]
name = "zc-core"
version = "0.0.2"
description = "Core AI coding functionality for zcoder"
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["development-tools"]
keywords = ["coding-harness", "coding-ai"]
authors = ["Jeremy Chone"]
homepage = "https://github.com/zcoder-run/zcoder"
repository = "https://github.com/zcoder-run/zcoder"

[lints.rust]
unsafe_code = "forbid"
# unused = { level = "allow", priority = -1 } # For exploratory dev.
# missing_docs = "warn"

[dependencies]
# -- Sub Crates
zc-asset = { workspace = true }
zc-common = { workspace = true }
# -- AI
genai = { workspace = true }
aicost = { workspace = true }
udiffx = { workspace = true }
markex = { workspace = true }
aiprog = { workspace = true }
# -- DB
rusqlite = { workspace = true, features = ["uuid"] }
modql = { workspace = true }
# -- Content Formats
serde = { workspace = true }
serde_json = { workspace = true }
value-ext = { workspace = true }
toml = { workspace = true }
# -- FS
simple-fs = { workspace = true }
# -- Async
tokio = { workspace = true }
# -- Concurrency
arc-swap = { workspace = true }
# -- Tracing
tracing = { workspace = true }
# -- Others
macro_rules_attribute = { workspace = true }
uuid = { workspace = true }
derive_more = { workspace = true }
