[package]
name = "zc-common"
version = "0.0.2-WIP"
edition = "2024"

[dependencies]
# -- Async & Events
crossfire = { workspace = true }
# -- Content Formats
serde = { workspace = true }
serde_json = { workspace = true }
yaml_serde = { workspace = true }
# -- FS
simple-fs = { workspace = true }
# -- Time
time = { workspace = true }
time-tz = { workspace = true }
# -- Others
derive_more = { workspace = true }
