[package]
name = "zc-common"
version = "0.0.2"
description = "Shared types and utilities for zcoder"
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["development-tools"]
keywords = ["coding-harness", "coding-ai"]
authors = ["Jeremy Chone"]
homepage = "https://github.com/zcoder-run/zcoder"
repository = "https://github.com/zcoder-run/zcoder"

[dependencies]
# -- Async & Events
crossfire = { workspace = true }
# -- Content Formats
serde = { workspace = true }
serde_json = { workspace = true }
yaml_serde = { workspace = true }
# -- FS
simple-fs = { workspace = true }
# -- Time
time = { workspace = true }
time-tz = { workspace = true }
# -- Others
derive_more = { workspace = true }
