[package]
name = "zc-tui"
version = "0.0.2-WIP"
description = "Terminal user interface for zcoder"
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities", "development-tools"]
keywords = ["coding-harness", "coding-ai", "tui"]
authors = ["Jeremy Chone"]
homepage = "https://github.com/zcoder-run/zcoder"
repository = "https://github.com/zcoder-run/zcoder"

[dependencies]
# -- Sub Crates
zc-core = { workspace = true }
zc-common = { workspace = true }
# -- Trace
tracing = { workspace = true }
# -- Async
tokio = { workspace = true }
futures = { workspace = true }
# -- CLI
ratatui = { workspace = true }
crossterm = { workspace = true }
textwrap = "0.16"
# -- System
sysinfo = { workspace = true }
# -- Others
derive_more = { workspace = true }
